# Generated by Django 2.2.1 on 2019-05-12 15:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail_snippet_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_images', to='wagtailimages.Image', verbose_name='Изображение для обложки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='snippet_image_field',
            field=wagtail_snippet_image.fields.SnippetImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_snippet_image', snippet_type='default', to='wagtailimages.Image', verbose_name='Example snippet image field'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=20),
        ),
    ]
